import { ArchivosNomina } from '../models/archivos-nomina';

export const ARCHIVOSNOMINA: ArchivosNomina[] = [
    { IDSERVIDORPUBLICO: '', IDRECIBONOMINA: '', PERIODO: '', FECHAINICIOPERIODO: new Date(), FECHAFINPERIODO: new Date(), RUTAXML: '', RUTAPDF: '' },
    { IDSERVIDORPUBLICO: '', IDRECIBONOMINA: '', PERIODO: '', FECHAINICIOPERIODO: new Date(), FECHAFINPERIODO: new Date(), RUTAXML: '', RUTAPDF: '' },
    { IDSERVIDORPUBLICO: '', IDRECIBONOMINA: '', PERIODO: '', FECHAINICIOPERIODO: new Date(), FECHAFINPERIODO: new Date(), RUTAXML: '', RUTAPDF: '' },
    { IDSERVIDORPUBLICO: '', IDRECIBONOMINA: '', PERIODO: '', FECHAINICIOPERIODO: new Date(), FECHAFINPERIODO: new Date(), RUTAXML: '', RUTAPDF: '' }
]
