import { Movimientosfump } from '../models/movimientosfump';

export const MOVIMIENTOSFUMPMOCK: Movimientosfump[] = [
    { TIPOMOVIMIENTO: "ALTA", FECHAMOVIMIENTO: "15-Marzo-1990", ARCHIVO: "", FOLIO: "12450" },
    { TIPOMOVIMIENTO: "CAMBIO", FECHAMOVIMIENTO: "22-Mayo-1993", ARCHIVO: "", FOLIO: "12453" },
    { TIPOMOVIMIENTO: "CAMBIO DE PERCEPCIONES", FECHAMOVIMIENTO: "25-mayo-1993", ARCHIVO: "", FOLIO: "12456" },
    { TIPOMOVIMIENTO: "LICENCIA", FECHAMOVIMIENTO: "02-Agosto-2005", ARCHIVO: "", FOLIO: "12461" },
    { TIPOMOVIMIENTO: "CAMBIO DE DATOS", FECHAMOVIMIENTO: "09-Septiembre-2010", ARCHIVO: "", FOLIO: "12465" },
    { TIPOMOVIMIENTO: "PERCEPCIONES Y DEDUCCIONES VARIABLES", FECHAMOVIMIENTO: "26-Junio-2015", ARCHIVO: "", FOLIO: "12470" }

]